---
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: https://fromcodetoprod.com/
title: From Code to Prod

# theme: ezhil
# theme: hugo-black-and-light-theme
# theme: hugo-kiera
# theme: hugo-lamp
# theme: hugo-theme-pure
# theme: hyde-hyde
# theme: minimal
theme: our-hyde

# https://gohugo.io/content-management/multilingual/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    weight: 1
    title: From Code To Prod Podcast
    params:
      copyright: Copyright 2019 From Code To Prod
      image:
      description:
      itunes:
        subtitle:
        author: Alexey Palazhchenko, Elena Grahovac
        owner:
          name: From Code To Prod Podcast
          email: hello@fromcodetoprod.com
  ru:
    weight: 2
    title: Подкаст От кода до прода
    params:
      copyright: Copyright 2019 From Code To Prod
      description:
      itunes:
        subtitle:
        author:

languageCode: en-us

# https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: true
    simple: true
  twitter:
    disable: true
    enableDNT: true
    simple: true
  vimeo:
    disable: true
    simple: true
  youtube:
    disable: true
    privacyEnhanced: true
