---
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: https://fromcodetoprod.com/
title: From Code to Prod

# theme: ezhil
# theme: hugo-black-and-light-theme
# theme: hugo-kiera
# theme: hugo-lamp
# theme: hugo-theme-pure
# theme: hyde-hyde
theme: minimal

# https://gohugo.io/content-management/multilingual/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    weight: 1
  ru:
    weight: 2

languageCode: en-us

# https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: true
    simple: true
  twitter:
    disable: true
    enableDNT: true
    simple: true
  vimeo:
    disable: true
    simple: true
  youtube:
    disable: true
    privacyEnhanced: true
